label: Fonts
status: ready

context:
  typefaces:
    - id: sans
      name: Public Sans
      description: |
        <p><a href="https://public-sans.digital.gov/">Public Sans</a> is a strong, neutral, principles-driven, open source typeface for text or display.</p>

    - id: serif
      name: Merriweather
      description: |
        <p>Merriweather is an open-source serif typeface designed for on-screen reading. This font is ideal for text-dense design: the letterforms have a tall x-height but remain relatively small, making for excellent readability across screen sizes while not occupying extra horizontal space.</p>
        <p>The combination of slim and thick weights gives the font family stylistic range, while conveying a desirable mix of classic, yet modern simplicity. Merriweather communicates warmth and credibility at both large and smaller font sizes.</p>
