label: Combo Box
status: ready
preview: "@uswds-framed"

variants:
  - name: default
    label: Default
    context:
      comboBox:
        label: "Select a fruit"
        name: "fruit"

  - name: default-value
    label: Default Value
    context:
      comboBox:
        defaultValue: "blackberry"
        label: "Select a fruit"
        name: "fruit"

  - name: required
    label: Required
    context:
      comboBox:
        label: "Select a fruit"
        name: "fruit"
        required: true
