label: Buttons
status: ready

variants:

  - name: Primary (Light)
    context:
      category: primary
      label: Primary Buttons (Light)
      classes: "usa-button"

  - name: Primary (Dark)
    context:
      category: primary
      label: Primary Buttons (Dark)
      classes: "usa-button primary-button-dark"

  - name: Primary (Danger)
    context:
      category: primary
      label: Primary Buttons (Danger)
      classes: "usa-button--secondary"

  - name: secondary (Light)
    context:
      category: secondary
      label: Secondary Buttons (Light)
      classes: "usa-button--outline"

  - name: Secondary (Dark)
    context:
      category: secondary
      label: Secondary Buttons (Dark)
      classes: "usa-button--outline usa-button--inverse"

  - name: Secondary (Danger)
    context:
      category: secondary
      label: Secondary Buttons (Danger)
      classes: "usa-button--outline outline-danger"

  - name: Tertiary (Light)
    context:
      category: Tertiary/Danger
      label: Tertiary/Link Light Buttons
      classes: "usa-button--unstyled"

  - name: Tertiary (Dark)
    context:
      category: Tertiary/Link
      label: Tertiary/Link Dark Buttons
      classes: "usa-button--unstyled unstyled-button-dark"
  - name: Tertiary (Danger) 
    context:
      category: Tertiary/Danger
      label: Tertiary/Link Danger Buttons
      classes: "usa-button--unstyled unstyled-button-danger"