name: PR Checks

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

concurrency:
  group: pr-checks-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  visual-regression-tests:
    name: Playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 20 # prevents long-running tests

    env:
      CI: true

    strategy:
      matrix:
        project: [visual, accessibility]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build design system and documentation
        run: npm run build-njwds && npm run storybook:build

      # cache playwright browsers to speed up workflow
      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      # install playwright browsers if cache is not hit
      - name: Install Playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      # start a static server to serve the built storybook
      - name: Start static server
        run: |
          npx http-server ./storybook-static -p 6006 &
          echo $! > server.pid

      # separate step to wait for the server to be ready before running tests
      - name: Wait for server
        run: npx wait-on http://localhost:6006

      - name: Run ${{ matrix.project }} tests
        run: npx playwright test --project=${{ matrix.project }}

      # if the tests fail, upload the Playwright artifacts for debugging
      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-${{ matrix.project }}
          path: |
            playwright-report/
            test-results/

      # cleanup step to stop the server after tests are done, regardless of success or failure
      - name: Stop server
        if: always()
        run: kill $(cat server.pid)

  build:
    name: Health checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Check Linting
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Check Typescript
        run: npx tsc --noEmit

      - name: Test run build-docs (soon deprecated)
        run: npm run build-docs

      - name: Test run storybook:build (with retry)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: npm run storybook:build

      - name: Test run build-njwds
        run: npm run build-njwds

